<?php
/*******************************************************************************
 * Copyright 2009-2015 Amazon Services. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 *
 * You may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at: http://aws.amazon.com/apache2.0
 * This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations under the License.
 *******************************************************************************
 * PHP Version 5
 * @category Amazon
 * @package  Marketplace Web Service Webstore
 * @version  2014-09-01
 * Library Version: 2015-06-18
 * Generated: Thu Jun 18 19:29:42 GMT 2015
 */

interface  MarketplaceWebServiceWebstore_Interface
{

    /**
     * Get Subscription Details
     * Returns a list of active subscriptions based on the list of subscription identifiers.
     *         Subscription identifier can be fetched from ListSubscriptionsCount and ListActiveSubscriptionByNextToken APIs.
     *
     * @param mixed $request array of parameters for MarketplaceWebServiceWebstore_Model_GetSubscriptionDetails request or MarketplaceWebServiceWebstore_Model_GetSubscriptionDetails object itself
     * @see MarketplaceWebServiceWebstore_Model_GetSubscriptionDetailsRequest
     * @return MarketplaceWebServiceWebstore_Model_GetSubscriptionDetailsResponse
     *
     * @throws MarketplaceWebServiceWebstore_Exception
     */
    public function getSubscriptionDetails($request);


    /**
     * List Subscriptions Count
     * Returns a list of active subscriptions for the seller.
     *         In the case there are more subscription results than can be returned
     *         in a single response, a next token is provided which can be used
     *         to obtain more results via ListSubscriptionsCountByNextToken.
     *
     * @param mixed $request array of parameters for MarketplaceWebServiceWebstore_Model_ListSubscriptionsCount request or MarketplaceWebServiceWebstore_Model_ListSubscriptionsCount object itself
     * @see MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountRequest
     * @return MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountResponse
     *
     * @throws MarketplaceWebServiceWebstore_Exception
     */
    public function listSubscriptionsCount($request);


    /**
     * List Subscriptions Count By Next Token
     * Returns a list of active subscription based on the next token generated by ListSubscriptionsCount or ListSubscriptionsCountByNextToken API.
     *         In the case there are more subscription results than can be returned
     *         in a single response, a next token is provided which can be used
     *         to obtain more results via same API.
     *
     * @param mixed $request array of parameters for MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountByNextToken request or MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountByNextToken object itself
     * @see MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountByNextTokenRequest
     * @return MarketplaceWebServiceWebstore_Model_ListSubscriptionsCountByNextTokenResponse
     *
     * @throws MarketplaceWebServiceWebstore_Exception
     */
    public function listSubscriptionsCountByNextToken($request);


    /**
     * Get Service Status
     * 
     *
     * @param mixed $request array of parameters for MarketplaceWebServiceWebstore_Model_GetServiceStatus request or MarketplaceWebServiceWebstore_Model_GetServiceStatus object itself
     * @see MarketplaceWebServiceWebstore_Model_GetServiceStatusRequest
     * @return MarketplaceWebServiceWebstore_Model_GetServiceStatusResponse
     *
     * @throws MarketplaceWebServiceWebstore_Exception
     */
    public function getServiceStatus($request);

}